apiVersion: batch/v1
kind: Job
metadata:
  name: upgrade-hook
  annotations:
    "install-job/hook": post-install
spec:
  template:
    spec:
      containers:
      - name: upgrade-hook
        image: alpine
        command: ["echo",  "Successful Upgradation"]
      restartPolicy: Never
