apiVersion: batch/v1
kind: Job
metadata:
  name: install-hook
  annotations:
    "install-job/hook": post-install
spec:
  template:
    spec:
      containers:
      - name: install-hook
        image: alpine
        command: ["echo",  "Successful Installation"]
      restartPolicy: Never
  backoffLimit: 4
